name: Build and Push Docker Image

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch: # allow manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          DOCKER_BUILDKIT=1 docker build . \
            --target vllm-openai \
            --file docker/Dockerfile \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/vllm-openai:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vllm-openai:latest
